import re

with open('result.log', 'r') as f:
    results = f.read()

with open('README.md', 'r') as f:
    readme = f.read()

link_pattern = re.compile(r'<a href="(.*?)">🟩</a>')

broken_links = [line.split(' ')[-1] for line in results.splitlines() if '✗' in line]

for link in broken_links:
    readme = re.sub(f'<a href="{link}">🟩</a>', f'<a href="{link}">🟥</a>', readme)

with open('README.md', 'w') as f:
    f.write(readme)
