name: Félix, The Checker.

on:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0

    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install selenium

    - name: Run Félix
      run: python felix_the_checker.py

    - name: Commit changes
      run: |
        git config --global user.name "Félix"
        git config --global user.email "<>"
        git add README.md
        git commit -m "Update" -m "README.md - Checked links." -m "Meow!~"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
